services:
  aria2:
    image: mfa777/my-aria2:latest
    container_name: aria2
    restart: unless-stopped
    ports:
      - "6800:6800"
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    environment:
      - TZ=UTC
    logging:
      options:
        max-size: 1m
